export const SUBTRACT_PRODUCT = "SUBTRACT_PRODUCT";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const REFRESH_TOKEN_PENDING = "REFRESH_TOKEN_PENDING";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_ERROR = "REFRESH_TOKEN_ERROR";
export const UNSET_CURRENT_USER = "UNSET_CURRENT_USER";

export const FETCH_CONSUMER_PENDING = "FETCH_CONSUMER_PENDING";
export const FETCH_CONSUMER_SUCCESS = "FETCH_CONSUMER_SUCCESS";
export const FETCH_CONSUMER_ERROR = "FETCH_CONSUMER_ERROR";

export const FETCH_STOCKISTS_PENDING = "FETCH_STOCKISTS_PENDING";
export const FETCH_STOCKISTS_SUCCESS = "FETCH_STOCKISTS_SUCCESS";
export const FETCH_STOCKISTS_ERROR = "FETCH_STOCKISTS_ERROR";

export const FETCH_TransactionHistory_PENDING =
  "FETCH_TransactionHistory_PENDING";
export const FETCH_TransactionHistory_SUCCESS =
  "FETCH_TransactionHistory_SUCCESS";
export const FETCH_TransactionHistory_ERROR = "FETCH_TransactionHistory_ERROR";

export const FETCH_LOYALTYVOUCHER_PENDING = "FETCH_LOYALTYVOUCHER_PENDING";
export const FETCH_LOYALTYVOUCHER_SUCCESS = "FETCH_LOYALTYVOUCHER_SUCCESS";
export const FETCH_LOYALTYVOUCHER_ERROR = "FETCH_LOYALTYVOUCHER_ERROR";

export const FETCH_VOUCHERLIST_PENDING = "FETCH_VOUCHERLIST_PENDING";
export const FETCH_VOUCHERLIST_SUCCESS = "FETCH_VOUCHERLIST_SUCCESS";
export const FETCH_VOUCHERLIST_ERROR = "FETCH_VOUCHERLIST_ERROR";
