export const SUBTRACT_PRODUCT = "SUBTRACT_PRODUCT";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const PHONE_START = "PHONE_START";
export const PHONE_SUCCESS = "PHONE_SUCCESS";
export const PHONE_FAILURE = "PHONE_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const REFRESH_TOKEN_PENDING = "REFRESH_TOKEN_PENDING";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_ERROR = "REFRESH_TOKEN_ERROR";
export const UNSET_CURRENT_USER = "UNSET_CURRENT_USER";

export const SITE_MANAGER_DATA_START = "SITE_MANAGER_DATA_START";
export const SITE_MANAGER_DATA_SUCCESS = "SITE_MANAGER_DATA_SUCCESS";
export const SITE_MANAGER_DATA_FAILURE = "SITE_MANAGER_DATA_FAILURE";

export const SITES_LIST_DATA_START = "SITES_LIST_DATA_START";
export const SITES_LIST_DATA_SUCCESS = "SITES_LIST_DATA_SUCCESS";
export const SITES_LIST_DATA_FAILURE = "SITES_LIST_DATA_FAILURE";

export const SITES_DATA_START = "SITES_DATA_START";
export const SITES_DATA_SUCCESS = "SITES_DATA_SUCCESS";
export const SITES_DATA_FAILURE = "SITES_DATA_FAILURE";

export const JOB_LIST_DATA_START = "JOB_LIST_DATA_START";
export const JOB_LIST_DATA_SUCCESS = "JOB_LIST_DATA_SUCCESS";
export const JOB_LIST_DATA_FAILURE = "JOB_LIST_DATA_FAILURE";

export const JOB_DATA_START = "JOB_DATA_START";
export const JOB_DATA_SUCCESS = "JOB_DATA_SUCCESS";
export const JOB_DATA_FAILURE = "JOB_DATA_FAILURE";


export const TIPPING_LIST_DATA_START = "TIPPING_LIST_DATA_START";
export const TIPPING_LIST_DATA_SUCCESS = "TIPPING_LIST_DATA_SUCCESS";
export const TIPPING_LIST_DATA_FAILURE = "TIPPING_LIST_DATA_FAILURE";

export const TICKETS_LIST_DATA_START = "TICKETS_LIST_DATA_START";
export const TICKETS_LIST_DATA_SUCCESS = "TICKETS_LIST_DATA_SUCCESS";
export const TICKETS_LIST_DATA_FAILURE = "TICKETS_LIST_DATA_FAILURE";


export const DASHBOARD_DATA_START = "DASHBOARD_DATA_START";
export const DASHBOARD_DATA_SUCCESS = "DASHBOARD_DATA_SUCCESS";
export const DASHBOARD_DATA_FAILURE = "DASHBOARD_DATA_FAILURE";

export const REPORTS_START = "REPORTS_START";
export const REPORTS_SUCCESS = "REPORTS_SUCCESS";
export const REPORTS_FAILURE = "REPORTS_FAILURE";

